FROM golang:1.23-alpine AS build

COPY org-ca-cert.crt /usr/local/share/ca-certificates/org-ca-cert.crt

RUN cat /usr/local/share/ca-certificates/org-ca-cert.crt >> /etc/ssl/certs/ca-certificates.crt

RUN apk add --no-cache git

WORKDIR /src

COPY go.mod go.sum ./

ENV GOPROXY=direct

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build \
  -trimpath \
  -ldflags="-s -w" \
  -o /service ./cmd/api

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=build /service /service

EXPOSE 8080

ENTRYPOINT ["/service"]
